routes:
  /culture/:
    template: tag
    controller: channel
    filter: tag:[arts,music,phoenix]

  /food-travel/:
    template: tag
    controller: channel
    filter: tag:[food,travel]

  /issues/:
    template: issue-archive
    data: page.issues

collections:
  /:
    permalink: /articles/{slug}/
    template: index

taxonomies:
  tag: /{slug}/
  author: /author/{slug}/
